 const MOVIE_NUMBER_LARGE = 16
 const MOVIE_NUMBER_SMALL = 5

 const WIDTH_WINOW_SMALL = 480
 const WIDTH_WINOW_MEDIUM = 910

 const ADD_MOVIE_SMALL = 2
 const ADD_MOVIE_MEDIUM = 4

 export {
    MOVIE_NUMBER_LARGE,
    MOVIE_NUMBER_SMALL,
    WIDTH_WINOW_SMALL,
    WIDTH_WINOW_MEDIUM,
    ADD_MOVIE_SMALL,
    ADD_MOVIE_MEDIUM
 }
